In [1]:
sessionInfo()

R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8.1 x64 (build 9600)

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Peru.1252  LC_CTYPE=Spanish_Peru.1252   
[3] LC_MONETARY=Spanish_Peru.1252 LC_NUMERIC=C                 
[5] LC_TIME=Spanish_Peru.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RevoUtils_11.0.3     RevoUtilsMath_11.0.0

loaded via a namespace (and not attached):
 [1] compiler_3.5.3  IRdisplay_0.7.0 pbdZMQ_0.3-3    tools_3.5.3    
 [5] htmltools_0.3.6 base64enc_0.1-3 crayon_1.3.4    Rcpp_1.0.0     
 [9] uuid_0.1-2      IRkernel_0.8.15 jsonlite_1.5    digest_0.6.18  
[13] repr_0.19.2     evaluate_0.12  

# Fundamentos de programación en R
1. Lenguaje de programación orientado a objetos
2. Objetos en R
3. Indexando y algunos comandos básicos
4. Operaciones

## 1. Lenguaje de programación orientado a objetos
### Lenguaje de Programación Orientado a Objetos (OOP) o Programación Funcional (FP)
OOP y FP son diferentes paradigmas para alcanzar un objetivo a través de la programación.

> OOP: Un paradigma de programación basado en el concepto de "objetos", que son estructuras que contienen datos en forma de campos, a menudo conocidos como atributos; y código, en forma de procedimientos, a menudo conocidos como métodos.
[wikipedia](https://en.wikipedia.org/wiki/Object-oriented_programming)

> FP: Un paradigma de programación, un estilo de construcción de estructuras y elementos del código, que trata al programa como evaluación de funciones matemáticas, evitando así, el cambio de estados y datos mutables.
[wikipedia](https://en.wikipedia.org/wiki/Functional_programming)

En cualquier programa hay dos componentes principales: *datos* y *comportamientos*. OOP reúne a los datos y sus comportamientos asociados en una única ubicación (llamada "objeto"). En cambio, FP mantiene los datos y sus comportamientos por separado.

Interesante artículo comparando OOP y FP [here](https://www.tutorialspoint.com/functional_programming/functional_programming_introduction.htm)

### Ejemplos
* OOP: lenguajes más populare como Python, R, Matlab, Julia, Fortran, Ruby, ...

* FP: Mathematica, Ruby,...

## 2. Objectos en R: Tipos de datos

Cuando programas en cualquier lenguaje necesitas usar diferentes variables para almacenar diferentes datos. Además, las variables se reservan en una ubicación de memoria, esto implica que, una vez que se crea una variable, se reserva un área en la memoria. Estos objetos son:

<table>
<thead>
<tr>
<th>Objeto</th>
<th>Descripción</th>
<th>Función que verifica</th>    
</tr>
</thead>
<tbody>
<tr>
<td>integer</td>
<td>valores enteros</td>
<td><code>is.integer()</code></td>    
</tr>
<tr>
<td>numeric</td>
<td>valores flotantes</td>
<td><code>is.numeric()</code></td>    
</tr>
<tr>
<td>character</td>
<td>cadenas de texto</td>
<td><code>is.character()</code></td>
</tr>
<tr>
<td>logical</td>
<td>valores booleanos</td>
<td><code>is.logical()</code></td>
</tbody>
</table>

Los objetos se pueden identificar con el comando *class()* o *mode()*

**Nota**: *las variables no tienen que declararse antes de ser usadas. Cuando asignas tiene una declaración automática*

### 2.1. Logical
Una declaración lógica verdadera/falsa

In [8]:
a <- TRUE
b <- FALSE

print(a)
print(b)

[1] TRUE
[1] FALSE
[1] TRUE
[1] TRUE
[1] FALSE


R puede indetificar el tipo de variable

In [4]:
print(class(a))
print(class(b))

[1] "logical"
[1] "logical"
[1] "logical"
[1] "logical"


[1] "logical"

[1] "logical"

In [26]:
mode(a)
class(a)

[1] "character"

[1] "character"

### 2.2. Integer y numeric
Los números pueden ser enteros (sin decimales) o flotantes (decimales de doble precisión).

In [34]:
c <- 4L #se usa el sufijo L
d <- 4
e <- 4.5
print(c)
print(d)
print(e)

[1] 4
[1] 4
[1] 4.5


In [35]:
class(c)
class(d)

[1] "integer"

[1] "numeric"

In [36]:
is.logical(c)
is.integer(c)
is.numeric(c)

[1] FALSE

[1] TRUE

[1] TRUE

In [37]:
is.logical(d)
is.integer(d)
is.numeric(d)

[1] FALSE

[1] FALSE

[1] TRUE

In [32]:
c==d

[1] TRUE

In [33]:
class(c)
class(d)
class(c)==class(d)

[1] "integer"

[1] "numeric"

[1] FALSE

### 2.3. Character
Un Character es una cadena de texto

In [43]:
a <- 'R-proyect'
b <- "R-proyect"
c <- "4"
d <- 4

print(a)
print(b)
print(c)
print(d)
print("hola mundo")
print("a")

[1] "R-proyect"
[1] "R-proyect"
[1] "4"
[1] 4
[1] "hola mundo"
[1] "a"


In [39]:
f <- "a"
g <- a

print(f)
print(g)

[1] "a"
[1] "R-proyect"


In [44]:
print(class(a))
print(class(b))
print(class(c))
print(class(d))
print(class(f))
print(class(g))

[1] "character"
[1] "character"
[1] "character"
[1] "numeric"
[1] "character"
[1] "character"


In [47]:
a==b 
class(a)==class(b)

[1] TRUE

[1] TRUE

[1] TRUE

In [48]:
"4"== 4
c==d
class(c)==class(d)

[1] TRUE

[1] TRUE

[1] FALSE

In [59]:
a <- "manzana"
b <- "platano"
c <- "uva"
#meta: "manzana,platano,uva"
d <- paste(a,b,c, sep=",")
print(d)

[1] "manzana,platano,uva"


In [60]:
e <- "hola"
f <- "mundo"
#meta: "hola mundo"

paste(e,f)
paste(e,f,sep=" ")

[1] "hola mundo"

[1] "hola mundo"

## 3. Objectos en R: Estructuras de datos

También existen objetos que son estructuras de datos, en la cual una variable puede almacenar más de un dato.

<table>
<thead>
<tr>
<th>Dimensiones</th>
<th>Homogeneas</th>
<th>Heterogeneas</th>
</tr>
</thead>
<tbody>
<tr>
<td>1</td>
<td>Vector</td>
<td>Lista</td>
</tr>
<tr>
<td>2</td>
<td>Matriz</td>
<td>Data frame</td>
</tbody>
</table>

### 3.1 Vectores

Un vector es la estructura de datos más sencilla en R. Un vector es una colección de uno o más datos del mismo tipo.

**Tipo**: Un vector tiene el mismo tipo que los datos que contiene. Si tenemos un vector que contiene datos de tipo numérico, el vector será también de tipo numérico. Los vectores son atómicos, pues sólo pueden contener datos de un sólo tipo, no es posible mezclar datos de tipos diferentes dentro de ellos.

**Largo**: Es el número de elementos que contiene un vector. El largo es la única dimensión que tiene esta estructura de datos.

In [79]:
a <- c(FALSE, FALSE,TRUE)
b <- c(1,2,3,4)
c <- c("hola","como","estas")

In [80]:
class(a)
class(b)
class(c)

[1] "logical"

[1] "numeric"

[1] "character"

In [100]:
length(a)
length(b)
length(c)

[1] 3

[1] 4

[1] 3

En caso de escribir valores de diferentes tipos se homogeniza con la clase más flexible. El orden de flexibilidad es: character, numeric y logical.

In [65]:
d <- c(1,2,TRUE,FALSE,TRUE,5) #TRUE: 1 , FALSE: 0
e <- c(1,2,TRUE,"hola")
print(d)
print(e)

[1] 1 2 1 0 1 5
[1] "1"    "2"    "TRUE" "hola"


In [66]:
class(d)
class(e)

[1] "numeric"

[1] "character"

También se puede unir vectores con <code>c()</code>

In [67]:
f <- c(d,e)
print(f)

 [1] "1"    "2"    "1"    "0"    "1"    "5"    "1"    "2"    "TRUE" "hola"


In [69]:
g <- 1:10
h <- 10:1

print(g)
print(h)

 [1]  1  2  3  4  5  6  7  8  9 10
 [1] 10  9  8  7  6  5  4  3  2  1


In [70]:
g[2]
h[2]

[1] 2

[1] 9

In [71]:
i <- seq(4,6,0.5)

print(i)

[1] 4.0 4.5 5.0 5.5 6.0


In [88]:
#segundo elemento
print(i[2])

#todo el vector excepto el segundo elemento
print(i[-2])

#del segundo al cuarto elemeto
print(i[2:4])

#el elemento 1 y 4
print(i[c(1,4)])

[1] 4.5
[1] 4.0 5.0 5.5 6.0
[1] 4.5 5.0 5.5
[1] 4.0 5.5


In [95]:
i[2] <- 517
print(i)

[1]   4.0 517.0   5.0   5.5   6.0


In [ ]:
j <- 1:5
h <- 1:5

### 3.2 Matrices

Las matrices son una estructura de datos bidimensionales, poseen largo y alto. Al igual que un vector, únicamente pueden contener datos de un sólo tipo, es decir son atómicos.

In [96]:
a <- 1:10 
print(a)

 [1]  1  2  3  4  5  6  7  8  9 10


In [41]:
b <- matrix(a)
print(b)

      [,1]
 [1,]    1
 [2,]    2
 [3,]    3
 [4,]    4
 [5,]    5
 [6,]    6
 [7,]    7
 [8,]    8
 [9,]    9
[10,]   10


In [42]:
nrow(b)
ncol(b)
dim(b)

[1] 10

[1] 1

[1] 10  1

In [100]:
c <- matrix(a,nrow=2)
print(c)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10


In [44]:
d <- matrix(a,ncol=2)
print(d)

     [,1] [,2]
[1,]    1    6
[2,]    2    7
[3,]    3    8
[4,]    4    9
[5,]    5   10


In [106]:
e <- matrix(a,ncol=2, byrow=TRUE)
print(e)

     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
[4,]    7    8
[5,]    9   10


In [46]:
class(b)
class(c)
class(d)
class(e)

[1] "matrix"

[1] "matrix"

[1] "matrix"

[1] "matrix"

In [104]:
f <- c(1,1,1)
g <- c(0,0,0)

h <- rbind(f,g)
print(h)
class(h)

  [,1] [,2] [,3]
f    1    1    1
g    0    0    0


[1] "matrix"

In [102]:
i <- cbind(f,g)

print(i)
class(i)

     f g
[1,] 1 0
[2,] 1 0
[3,] 1 0


[1] "matrix"

In [107]:
print(e)

     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
[4,]    7    8
[5,]    9   10


In [73]:
#elemento de segunda fila y segunda columna
print(e[2,2])

[1] 4


In [110]:
#segunda fila
print(e[2,])

[1] 3 4


In [72]:
#segunda columna
print(e[,2])

[1]  2  4  6  8 10


In [74]:
#toda la matriz excepto la segunda fila
print(e[-2,])

     [,1] [,2]
[1,]    1    2
[2,]    5    6
[3,]    7    8
[4,]    9   10


### 3.3 Listas
Las listas, al igual que los vectores, son estructuras de datos unidimensionales, sólo tienen largo, pero a diferencia de los vectores cada uno de sus elementos puede ser de diferente tipo o incluso de diferente clase, por lo que son estructuras heterogéneas.

In [116]:
a <- c(2,TRUE,"hola")
print(a)

[1] "2"    "TRUE" "hola"


In [115]:
b <- list(2,TRUE,"hola")
print(b)

[[1]]
[1] 2

[[2]]
[1] TRUE

[[3]]
[1] "hola"



In [117]:
c <- list(2,TRUE,"hola",c(5,7,9))
print(c)

[[1]]
[1] 2

[[2]]
[1] TRUE

[[3]]
[1] "hola"

[[4]]
[1] 5 7 9



In [131]:
vectorNumerico <- c(1,2,3)
vectorChar <- c("hola","chau")
matriz <- matrix(1:9,nrow=3, byrow=TRUE)
dummy <- TRUE

a <- list(vectorNumerico, vectorChar, matriz, dummy)
print(a)

[[1]]
[1] 1 2 3

[[2]]
[1] "hola" "chau"

[[3]]
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

[[4]]
[1] TRUE



In [132]:
b <- list("vector1"=vectorNumerico, "vector2"=vectorChar, "matriz"=matriz, "dummy"=dummy)
print(b)

$vector1
[1] 1 2 3

$vector2
[1] "hola" "chau"

$matriz
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

$dummy
[1] TRUE



In [133]:
a[2]

[[1]]
[1] "hola" "chau"

In [134]:
b$vector2
b[2]
print(b$matriz)

[1] "hola" "chau"

$vector2
[1] "hola" "chau"

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9


In [135]:
names(a)
names(b)

NULL

[1] "vector1" "vector2" "matriz"  "dummy"

In [136]:
names(a) <- c("vector1","vector2","matriz","dummy")
print(a)

$vector1
[1] 1 2 3

$vector2
[1] "hola" "chau"

$matriz
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

$dummy
[1] TRUE



In [137]:
a$nuevo <- "Hola mundo"
print(a)

$vector1
[1] 1 2 3

$vector2
[1] "hola" "chau"

$matriz
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

$dummy
[1] TRUE

$nuevo
[1] "Hola mundo"



In [138]:
a[6] <- list(c(5,6))
print(a)

$vector1
[1] 1 2 3

$vector2
[1] "hola" "chau"

$matriz
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

$dummy
[1] TRUE

$nuevo
[1] "Hola mundo"

[[6]]
[1] 5 6



In [139]:
names(a)

[1] "vector1" "vector2" "matriz"  "dummy"   "nuevo"   ""

### 3.3 Data frames
El origen del data frame proviene de una intensa investigación empírica en el mundo del software estadístico. En particular, es una estructura de datos en R donde hay observaciones o registros (filas) y variables o campos (columnas).

Se utiliza un data frame para almacenar tablas de datos, los vectores que están contenidos en forma de una lista en un marco de datos son de igual longitud.

In [144]:
vector1 <- c("Armando", "Elsa", "Ignacio", "Olga")
vector2 <- c(20, 24, 22, 30)
vector3 <- c("Hombre", "Mujer", "Hombre", "Mujer")


dataEstructurada <- data.frame("nombres"= vector1, "edad" = vector2, "sexo"= vector3)
dataEstructurada #printeo Jupyter
print(dataEstructurada) #printeo R

nombres edad sexo  
1 Armando 20   Hombre
2 Elsa    24   Mujer 
3 Ignacio 22   Hombre
4 Olga    30   Mujer

  nombres edad   sexo
1 Armando   20 Hombre
2    Elsa   24  Mujer
3 Ignacio   22 Hombre
4    Olga   30  Mujer


In [145]:
names(dataEstructurada)

[1] "nombres" "edad"    "sexo"

In [146]:
print(dataEstructurada$sexo)

[1] Hombre Mujer  Hombre Mujer 
Levels: Hombre Mujer


In [147]:
print(dataEstructurada[3])

    sexo
1 Hombre
2  Mujer
3 Hombre
4  Mujer


In [148]:
print(dataEstructurada[2,])

  nombres edad  sexo
2    Elsa   24 Mujer


In [149]:
print(dataEstructurada[-2,])

  nombres edad   sexo
1 Armando   20 Hombre
3 Ignacio   22 Hombre
4    Olga   30  Mujer


In [150]:
print(dataEstructurada[2:3,])

  nombres edad   sexo
2    Elsa   24  Mujer
3 Ignacio   22 Hombre


In [151]:
str(dataEstructurada)

'data.frame':	4 obs. of  3 variables:
 $ nombres: Factor w/ 4 levels "Armando","Elsa",..: 1 2 3 4
 $ edad   : num  20 24 22 30
 $ sexo   : Factor w/ 2 levels "Hombre","Mujer": 1 2 1 2


In [32]:
dim(dataEstructurada)
nrow(dataEstructurada)
ncol(dataEstructurada)

[1] 4 3

[1] 4

[1] 3

In [152]:
summary(dataEstructurada)

    nombres       edad          sexo  
 Armando:1   Min.   :20.0   Hombre:2  
 Elsa   :1   1st Qu.:21.5   Mujer :2  
 Ignacio:1   Median :23.0             
 Olga   :1   Mean   :24.0             
             3rd Qu.:25.5             
             Max.   :30.0             